language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script: ci-script/script.sh
matrix:
  allow_failures:
    - rust: nightly
